version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samtwo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qylvsls2vi2l"
s3_prefix = "samtwo"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "APIName=\"testapi\""
