AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  samtwo
  
  Sample SAM Template for Sam-AppSync-GraphQL

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  LambdaHelloWorld:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/lambdas/lambda_hello_world.yaml

  LambdaPerson:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/lambdas/lambda_person.yaml

  RoleLambdas:
    Type: AWS::Serverless::Application
    DependsOn: LambdaPerson
    Properties:
      Location: resources/roles/role_lambdas.yaml

  RoleDynamoDb:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/roles/role_DynamoDb.yaml

  DynamoDbTablePerson:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/dynamodb/dynamo_table_people.yaml

  AppSyncGraphQLApi:
    Type: AWS::Serverless::Application
    Properties:
      Location: resources/appsync/grapghqlapi.yaml

  AppSyncGraphQLSchema:
    Type: AWS::Serverless::Application
    DependsOn: AppSyncGraphQLApi
    Properties:
      Location: resources/appsync/graphqlschema.yaml

  AppSyncDataSources:
    Type: AWS::Serverless::Application
    DependsOn: 
      - AppSyncGraphQLApi
      - RoleLambdas
      - RoleDynamoDb
    Properties:
      Location: resources/appsync/data_sources.yaml

  AppSyncResolvers:
    Type: AWS::Serverless::Application
    DependsOn: 
      - AppSyncDataSources
      - AppSyncGraphQLApi
    Properties:
      Location: resources/appsync/resolver_person_data.yaml

  AppSyncResolversDynamoDb:
    Type: AWS::Serverless::Application
    DependsOn: 
      - AppSyncDataSources
      - AppSyncGraphQLApi
    Properties:
      Location: resources/appsync/resolver_person_dynamodb.yaml

  AppSyncApiKey:
    Type: AWS::Serverless::Application
    DependsOn: AppSyncGraphQLApi
    Properties:
      Location: resources/appsync/api_key.yaml
