AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  samtwo
  
  Sample SAM Template for samtwo simple table in dynamoDb

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  TablePeople:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: people
      PrimaryKey:
        Name: id
        Type: String