AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  samtwo
  
  Sample SAM Template for samtwo roles for dynamoDb

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  RoleDynamoDb: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allow-access-to-dynamodb-person-from-appsync
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/people

  RoleDynamoDbArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: RoleDynamoDbArnSSM
      Value: !GetAtt [RoleDynamoDb, Arn]

Outputs:
  RoleDynamoDbArn:
    Description: RoleDynamoDb Arn
    Value: !GetAtt [RoleDynamoDb, Arn]